# action.yml
name: 'BlazeAction'
description: 'Run Blazemeter Test from GitHub Action'
inputs:
  apikey:  # id of input
    description: 'API Key'
    required: true
    default: 'Test'
  apisecret:  # id of input
    description: 'API Secret'
    required: true
    default: 'Test'
  testid:  # id of input
    description: 'Test Id'
    required: true
    default: '0'
  supportedfolderPath:  # id of input
    description: 'Supported File Folder'
    required: false
    default: '0'
  workspaceid:  # id of input
    description: 'Workspace Id'
    required: false
    default: '0'
  datamodelid:  # id of input
    description: 'Data Model Id'
    required: false
    default: '0'
  modeldata:  # id of input
    description: 'Data to be updated in JSON String format'
    required: false
    default: '{}'
  createtest:  # id of input
    description: 'Create test flag'
    required: false
    default: 'false'
  inputstartfile:  # id of input
    description: 'Start file for create test'
    required: false
    default: '0'
  testname:  # id of input
    description: 'Test name for creating new test'
    required: false
    default: '0'
  projectid:  # id of input
    description: 'Project Id'
    required: false
    default: '0'
  continuepipeline:
    description: 'Continue Pipeline'
    required: false
    default: 'true'
  jmeterproperties:
    description: 'jmeterproperties'
    required: false
    default: '0'
  
runs:
  using: 'docker'
  image: 'Dockerfile'
